import type { VimGolfChallenge } from './types'

export const BUILTIN_CHALLENGES: VimGolfChallenge[] = [
  // ── Easy ──────────────────────────────────────────────────────────────
  {
    id: 'vg_01_hello_vim',
    title: 'Hello, Vim!',
    description: 'Replace "World" with "Vim".',
    start: 'Hello World!\n',
    end:   'Hello Vim!\n',
    difficulty: 'easy',
    tags: ['cw', 'substitution'],
  },
  {
    id: 'vg_02_semicolons',
    title: 'Line Terminators',
    description: 'Add a semicolon at the end of every line.',
    start: 'const x = 1\nconst y = 2\nconst z = 3\n',
    end:   'const x = 1;\nconst y = 2;\nconst z = 3;\n',
    difficulty: 'easy',
    tags: ['append', 'macro'],
  },
  {
    id: 'vg_03_trailing_spaces',
    title: 'Tidy Trailing Spaces',
    description: 'Remove all trailing whitespace from every line.',
    start: 'hello   \nworld  \n   foo  \n',
    end:   'hello\nworld\n   foo\n',
    difficulty: 'easy',
    tags: ['substitution', 'regex'],
  },
  {
    id: 'vg_04_uppercase',
    title: 'SHOUT IT',
    description: 'Convert the entire first line to uppercase.',
    start: 'hello world\n',
    end:   'HELLO WORLD\n',
    difficulty: 'easy',
    tags: ['case', 'visual', 'gU'],
  },
  {
    id: 'vg_05_empty_parens',
    title: 'Empty the Parens',
    description: 'Delete everything inside the parentheses.',
    start: 'foo(bar, baz, qux)\n',
    end:   'foo()\n',
    difficulty: 'easy',
    tags: ['text-objects', 'di('],
  },
  {
    id: 'vg_06_count_up',
    title: 'Count Up',
    description: 'Increment each number by 1.',
    start: 'step 1\nstep 2\nstep 3\n',
    end:   'step 2\nstep 3\nstep 4\n',
    difficulty: 'easy',
    tags: ['ctrl-a', 'macro'],
  },
  // ── Medium ────────────────────────────────────────────────────────────
  {
    id: 'vg_07_comment_out',
    title: 'Comment It Out',
    description: 'Prepend // to every line.',
    start: 'let x = 1;\nlet y = 2;\nlet z = 3;\n',
    end:   '// let x = 1;\n// let y = 2;\n// let z = 3;\n',
    difficulty: 'medium',
    tags: ['visual-block', 'macro', 'global'],
  },
  {
    id: 'vg_08_sort_lines',
    title: 'Alphabetical Order',
    description: 'Sort these lines alphabetically.',
    start: 'banana\napple\ncherry\ndate\n',
    end:   'apple\nbanana\ncherry\ndate\n',
    difficulty: 'medium',
    tags: ['sort', 'ex'],
  },
  {
    id: 'vg_09_join_comma',
    title: 'Single Line',
    description: 'Join all three lines into one, separated by ", ".',
    start: 'alpha\nbeta\ngamma\n',
    end:   'alpha, beta, gamma\n',
    difficulty: 'medium',
    tags: ['join', 'substitution'],
  },
  {
    id: 'vg_10_duplicate_lines',
    title: 'Mirror Lines',
    description: 'Duplicate each line so it appears twice consecutively.',
    start: 'foo\nbar\nbaz\n',
    end:   'foo\nfoo\nbar\nbar\nbaz\nbaz\n',
    difficulty: 'medium',
    tags: ['yank', 'macro'],
  },
  {
    id: 'vg_11_blank_lines',
    title: 'Blank Line Removal',
    description: 'Delete all blank lines.',
    start: 'line one\n\nline two\n\n\nline three\n',
    end:   'line one\nline two\nline three\n',
    difficulty: 'medium',
    tags: ['global', 'delete', 'regex'],
  },
  {
    id: 'vg_12_quote_words',
    title: 'Quote Every Word',
    description: 'Wrap each space-separated token in double quotes.',
    start: 'apple orange banana\n',
    end:   '"apple" "orange" "banana"\n',
    difficulty: 'medium',
    tags: ['substitution', 'regex'],
  },
  {
    id: 'vg_13_swap_args',
    title: 'Argument Shuffle',
    description: 'Swap the first and second function arguments.',
    start: 'doThing(alpha, beta, gamma)\n',
    end:   'doThing(beta, alpha, gamma)\n',
    difficulty: 'medium',
    tags: ['motion', 'delete', 'paste'],
  },
  // ── Hard ─────────────────────────────────────────────────────────────
  {
    id: 'vg_14_camel_case',
    title: 'camelCase',
    description: 'Convert this snake_case identifier to camelCase.',
    start: 'my_variable_name\n',
    end:   'myVariableName\n',
    difficulty: 'hard',
    tags: ['substitution', 'macro', 'case'],
  },
  {
    id: 'vg_15_reverse_lines',
    title: 'Flip the Script',
    description: 'Reverse the order of all lines.',
    start: 'first\nsecond\nthird\nfourth\n',
    end:   'fourth\nthird\nsecond\nfirst\n',
    difficulty: 'hard',
    tags: ['global', 'move'],
  },
  {
    id: 'vg_16_extract_const',
    title: 'Extract Constant',
    description: 'Extract the repeated magic number into a named constant on a new first line.',
    start: 'const area = 3.14159 * r * r;\nconst circ = 2 * 3.14159 * r;\n',
    end:   'const PI = 3.14159;\nconst area = PI * r * r;\nconst circ = 2 * PI * r;\n',
    difficulty: 'hard',
    tags: ['yank', 'substitution', 'insert'],
  },
  {
    id: 'vg_17_align_equals',
    title: 'Align Assignments',
    description: 'Pad each variable name so all = signs align to column 8.',
    start: 'foo = 1\nbarbaz = 2\nqux = 3\n',
    end:   'foo    = 1\nbarbaz = 2\nqux    = 3\n',
    difficulty: 'hard',
    tags: ['visual-block', 'insert', 'spaces'],
  },
  {
    id: 'vg_18_sql_oneliner',
    title: 'SQL Oneliner',
    description: 'Collapse this multi-line SQL query onto a single line.',
    start: 'SELECT\n  name,\n  age\nFROM users\nWHERE active = 1\n',
    end:   'SELECT name, age FROM users WHERE active = 1\n',
    difficulty: 'hard',
    tags: ['join', 'substitution', 'regex'],
  },
  {
    id: 'vg_19_number_lines',
    title: 'Number the Lines',
    description: 'Prefix each line with its 1-based line number and a period.',
    start: 'apple\nbanana\ncherry\ndate\negg\n',
    end:   '1. apple\n2. banana\n3. cherry\n4. date\n5. egg\n',
    difficulty: 'hard',
    tags: ['macro', 'register', 'insert'],
  },
  {
    id: 'vg_20_json_object',
    title: 'CSV to JSON',
    description: 'Convert this CSV row to a compact JSON object with the given keys.',
    start: 'Alice,30,Engineer\n',
    end:   '{"name":"Alice","age":"30","role":"Engineer"}\n',
    difficulty: 'hard',
    tags: ['substitution', 'complex'],
  },
]
